### ISSUE TITLE
If a notification is currently being displayed and another code push comes through, the notification disappears

### ISSUE THREAD

**Issue by keviniamburg** [arsnebula/meteor-app-update#1] opened 2015-02-01 22:20 UTC
Not sure if this is expected behavior or not, but wanted to bring it up. Cheers.

**Comment by skifaster** [comment] 2015-02-02 22:15
Ah. Thanks for the heads up. Will take a look. This is not expected behavior.

**Comment by skifaster** [comment] 2015-02-03 08:41
@slickdev i was unable to reproduce this issue consistently. I did see the issue once or twice during my testing, but not enough for a proper repo. Do you have a repo I can try to recreate it more consistently? 

Here are my current settings for the package. I have this in my lib folder for testing: 

```
if(Meteor.isClient) {
    AppUpdate.reload.settings.environments.development = true;

    AppUpdate.reload.preventReload();
}
```

**Comment by keviniamburg** [comment] 2015-02-03 15:54
I ended up removing the plugin in the end, since I couldn't get it to work reliably enough. I might give it another try on another project, will keep you posted.

**Comment by skifaster** [comment] 2015-02-09 00:53
Ok. Thanks for the heads up. I'll close this issue for now.

**Closed as completed by skifaster** 2015-02-09 00:53 UTC
